version: '3.9'
services:
  cee:
    build:
      context: .
      args:
        NODE_ENV: development
      
    environment:
      - PORT=3000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/CodeExecutionEngine:/app/CodeExecutionEngine:ro
      - /app/node_modules
    command: npm run dev